### ISSUE TITLE
Shortcuts not working

### ISSUE THREAD

**Issue by noreo** [ANGIstudio/Sketch-Copy-Paste-Position-Size#2]
On version 45, and 45.1 the shortcuts are not working.

**Comment by ajilderda** [comment]
Hi @noreo, I have no problems with the shortcuts on 45.1. Do you maybe have https://github.com/matt-curtis/Fluid-for-Sketch installed?

**Comment by noreo** [comment]
hi @ajilderda, 
Actually it's working now... sorry about that. No, I didn't have Fluid installed.
maybe some old plugin that was creating the bug...

**Comment by ajilderda** [comment]
No problem, enjoy!

**Comment by noreo** [comment]
By the way, I love your plugin, using it 100 times a day :)

**Comment by ajilderda** [comment]
That's great to hear! :smiley:
